/***************************************************************************************************************************************
 * NAME   : CC_AddressInformationController
 * DESCRIPTION  : Controller method for CC_AddressInformation component.
 *    
 * @AUTHOR   : Nidhin V K
 * @DATE   : 11-21-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K               11-21-2017          Initial version        
 ****************************************************************************************************************************************/
public with sharing class CC_AddressInformationController {
    /* METHOD NAME   : getDependentOptions 
     * DESCRIPTION  : get Queue Info using developer name
     *
     * RETURN TYPE   : Map < String, List < String >>
     * PARAMETER   : sObjName, sControllingField, sDependentField
     *
    @AuraEnabled
    public static Map < String, List < String >> getDependentOptions(string sObjName, string sControllingField, string sDependentField) {
        return CC_Utility.getDependentPicklistValues(sObjName, sControllingField, sDependentField);
    }*/
}